# Generated by Django 4.2.6 on 2023-10-24 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
