# Generated by Django 4.2.6 on 2023-10-24 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movies_created_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Movies",
            new_name="Movie",
        ),
    ]
